apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/emily-zall/argo.git
    targetRevision: HEAD
    path: dev-app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true